### ISSUE TITLE
可以有偿帮我解决个环境搭建的问题吗，加我v 17602540331 谢谢

### ISSUE THREAD

**Issue by asdfr1635** [ceresOPA/Financial-Fraud-Predict-System#1]

**Comment by ceresOPA** [comment]
有什么问题的话可以在这里截图告诉我，我会回答你的。

**Comment by asdfr1635** [comment]
> 有什么问题的话可以在这里截图告诉我，我会回答你的。

主要是我想有偿让大哥你帮我修改一下代码，因为我是反欺诈方面的，大哥你加我v，我看你这个是贷款的，大差不差。大哥加我帮我修改一下可好，有偿 17602540331 vx

**Comment by asdfr1635** [comment]
> 有什么问题的话可以在这里截图告诉我，我会回答你的。

数据我这边都有

**Comment by asdfr1635** [comment]
![4df0b7f277388ea33b7ffc59f477e08](https://user-images.githubusercontent.com/36811925/211317731-a3ed15e9-8d12-46fd-ba48-9621f7d7d560.jpg)
大哥加我

**Comment by asdfr1635** [comment]
不难，还是这个框架。就数据格式的问题需要大哥你改一下
